USE villarcompany
GO

INSERT Employee ([Fname], [Minit], [Lname], [Ssn], [Bdate], [Address], [Sex], [Salary], [Super_ssn], [Dno])
VALUES
('Ace', 'S', 'Chan', 001, '2004-01-16', 'Rizal Park', 'F', 10, 0013, 00111),
('Lorna', 'J', 'Espaldon', 002, '2003-06-12', 'Mars', 'F',20, 0012, 00122),
('John', 'E', 'España', 003, '2002-09-20', 'Zoo', 'M', 30, 0011, 00112);
go

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
LEFT JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT. Mgr_ssn

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
RIGHT JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT. Mgr_ssn

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT. Mgr_ssn

SELECT EMPLOYEE. *, DEPARTMENT.*
FROM EMPLOYEE
CROSS JOIN DEPARTMENT

UPDATE EMPLOYEE
SET Fname = 'Roscela'
WHERE Ssn=003
